
package nezet;

import java.awt.Component;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modell.Lada;


public class KincsesLadaGUI extends javax.swing.JFrame {
    
    private final int LADAK_SZAMA=3;
    private final String ZARTLADA="/kepek/zartJo.png";
    private final String URESLADA="/kepek/uresJo.png";
    private final String KINCSESLADA="/kepek/kincsesJo.png";
    
    private JButton[] ladaGombok;
    private Lada lada;
    private JButton kattGomb;
    
    public KincsesLadaGUI() {
        initComponents();
        
        lada = new Lada();
        ladaGombokFeltolt();
        
        kattGomb=ladaGombok[0];
        
        lblLeiras.setText("<html><p style='padding: 10px'>"+ lada.getLeiras() +"</p></html>");
        lblBronz.setText(lada.getBronzFelirat());
        lblEzust.setText(lada.getEzustFelirat());
        lblArany.setText(lada.getAranyFelirat());
        pack();
    }
    
    private void ladaGombokFeltolt(){
        int ladaIndex=0;
        ladaGombok = new JButton[LADAK_SZAMA];
        Component[] comps = pnlLadak.getComponents();
        for (int i = 0; i < comps.length; i++) {
            if (comps[i] instanceof JButton) {
                JButton egyGomb = (JButton)comps[i];
                ladaGombok[ladaIndex]=egyGomb;
                ladaIndex++;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLeiras = new javax.swing.JLabel();
        btnUjra = new javax.swing.JButton();
        pnlLadak = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBronz = new javax.swing.JButton();
        btnEzust = new javax.swing.JButton();
        btnArany = new javax.swing.JButton();
        lblBronz = new javax.swing.JLabel();
        lblEzust = new javax.swing.JLabel();
        lblArany = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Találós kérdés");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Leírás"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLeiras, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLeiras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        btnUjra.setText("Újra");
        btnUjra.setEnabled(false);
        btnUjra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjraActionPerformed(evt);
            }
        });

        pnlLadak.setBorder(javax.swing.BorderFactory.createTitledBorder("Ládák"));
        pnlLadak.setLayout(new java.awt.GridLayout(3, 3, 20, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bronz");
        pnlLadak.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ezüst");
        pnlLadak.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Arany");
        pnlLadak.add(jLabel3);

        btnBronz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zartJo.png"))); // NOI18N
        btnBronz.setPreferredSize(new java.awt.Dimension(113, 83));
        btnBronz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uresLadaAction(evt);
            }
        });
        pnlLadak.add(btnBronz);

        btnEzust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zartJo.png"))); // NOI18N
        btnEzust.setPreferredSize(new java.awt.Dimension(113, 83));
        btnEzust.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEzust.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEzust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kincsesLadaAction(evt);
            }
        });
        pnlLadak.add(btnEzust);

        btnArany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zartJo.png"))); // NOI18N
        btnArany.setPreferredSize(new java.awt.Dimension(113, 83));
        btnArany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uresLadaAction(evt);
            }
        });
        pnlLadak.add(btnArany);

        lblBronz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLadak.add(lblBronz);

        lblEzust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLadak.add(lblEzust);

        lblArany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLadak.add(lblArany);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUjra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlLadak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLadak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uresLadaAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uresLadaAction
        kattGomb = (JButton)evt.getSource();
        Icon kep = new ImageIcon(getClass().getResource(URESLADA));
        kattGomb.setIcon(kep);
        JOptionPane.showMessageDialog(null, lada.talaltE(Lada.ARANY), "Visszajelzés", JOptionPane.OK_OPTION);
        ladaGombokKapcsolas(false);
        btnUjra.setEnabled(true);
    }//GEN-LAST:event_uresLadaAction

    private void btnUjraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjraActionPerformed
        Icon kep = new ImageIcon(getClass().getResource("/kepek/zartJo.png"));
        kattGomb.setIcon(kep);
        ladaGombokKapcsolas(true);
    }//GEN-LAST:event_btnUjraActionPerformed

    private void kincsesLadaAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kincsesLadaAction
        
    }//GEN-LAST:event_kincsesLadaAction
    private void ladaGombokKapcsolas(boolean be){
        for (int i = 0; i < ladaGombok.length; i++) {
            ladaGombok[i].setEnabled(be);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArany;
    private javax.swing.JButton btnBronz;
    private javax.swing.JButton btnEzust;
    private javax.swing.JButton btnUjra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArany;
    private javax.swing.JLabel lblBronz;
    private javax.swing.JLabel lblEzust;
    private javax.swing.JLabel lblLeiras;
    private javax.swing.JPanel pnlLadak;
    // End of variables declaration//GEN-END:variables
}
