
package nezet;

import java.awt.Component;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modell.Lada;


public class KincsesLadaGUI extends javax.swing.JFrame {
    
    private final int LADAK_SZAMA=3;
    private final String ZARTLADA="/kepek/zartJo.png";
    private final String URESLADA="/kepek/uresJo.png";
    private final String KINCSESLADA="/kepek/kincsesJo.png";
    
    private JButton[] ladaGombok;
    private Lada lada;
    private JButton kattGomb;
    
    public KincsesLadaGUI() {
        initComponents();
        
        lada = new Lada();
        ladaGombokFeltolt();
        
        kattGomb=ladaGombok[0];
        
        lblLeiras.setText("<html><p style='padding: 10px'>"+ lada.getLeiras() +"</p></html>");
        lblBronz.setText(lada.getBronzFelirat());
        lblEzust.setText(lada.getEzustFelirat());
        lblArany.setText(lada.getAranyFelirat());
        pack();
    }
    
    private void ladaGombokFeltolt(){
        int ladaIndex=0;
        ladaGombok = new JButton[LADAK_SZAMA];
        Component[] comps = pnlLadak.getComponents();
        for (int i = 0; i < comps.length; i++) {
            if (comps[i] instanceof JButton) {
                JButton egyGomb = (JButton)comps[i];
                ladaGombok[ladaIndex]=egyGomb;
                ladaIndex++;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        btnUjra = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblLeiras = new javax.swing.JLabel();
        pnlLadak = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBronz = new javax.swing.JButton();
        btnEzust = new javax.swing.JButton();
        btnArany = new javax.swing.JButton();
        lblBronz = new javax.swing.JLabel();
        lblEzust = new javax.swing.JLabel();
        lblArany = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Találós kérdés");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnUjra.setText("Újra");
        btnUjra.setEnabled(false);
        btnUjra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjraActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Leírás"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLeiras, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlLadak.setBorder(javax.swing.BorderFactory.createTitledBorder("Ládák"));
        pnlLadak.setLayout(new java.awt.GridLayout(3, 3, 20, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bronz");
        pnlLadak.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ezüst");
        pnlLadak.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Arany");
        pnlLadak.add(jLabel3);

        btnBronz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zartJo.png"))); // NOI18N
        btnBronz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uresLadaAction(evt);
            }
        });
        pnlLadak.add(btnBronz);

        btnEzust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zartJo.png"))); // NOI18N
        btnEzust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kincsesLadaAction(evt);
            }
        });
        pnlLadak.add(btnEzust);

        btnArany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zartJo.png"))); // NOI18N
        btnArany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uresLadaAction(evt);
            }
        });
        pnlLadak.add(btnArany);

        lblBronz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLadak.add(lblBronz);

        lblEzust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLadak.add(lblEzust);

        lblArany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLadak.add(lblArany);

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addComponent(btnUjra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlLadak, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(pnlLadak, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uresLadaAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uresLadaAction
        setGombIcon(evt, URESLADA);
        JOptionPane.showMessageDialog(pnlContainer, lada.talaltE(Lada.ARANY), "Visszajelzés", JOptionPane.OK_OPTION);
        gombokKapcsolo(false, true);
    }//GEN-LAST:event_uresLadaAction

    private void btnUjraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjraActionPerformed
        Icon kep = new ImageIcon(getClass().getResource(ZARTLADA));
        kattGomb.setIcon(kep);
        gombokKapcsolo(true, false);
    }//GEN-LAST:event_btnUjraActionPerformed

    private void kincsesLadaAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kincsesLadaAction
        setGombIcon(evt, KINCSESLADA);
        JOptionPane.showMessageDialog(pnlContainer, lada.talaltE(Lada.EZUST), "Visszajelzés", JOptionPane.DEFAULT_OPTION);
        gombokKapcsolo(false, true);
    }//GEN-LAST:event_kincsesLadaAction
    private void gombokKapcsolo(boolean ladaGombok, boolean ujraGomb){
        ladaGombokKapcsolo(ladaGombok);
        btnUjra.setEnabled(ujraGomb);
    }
    
    private void setGombIcon(java.awt.event.ActionEvent evt, String ladaTipus){
        kattGomb = (JButton)evt.getSource();
        Icon kep = new ImageIcon(getClass().getResource(ladaTipus));
        kattGomb.setIcon(kep);
    }
    
    private void ladaGombokKapcsolo(boolean be){
        for (int i = 0; i < ladaGombok.length; i++) {
            ladaGombok[i].setEnabled(be);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArany;
    private javax.swing.JButton btnBronz;
    private javax.swing.JButton btnEzust;
    private javax.swing.JButton btnUjra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArany;
    private javax.swing.JLabel lblBronz;
    private javax.swing.JLabel lblEzust;
    private javax.swing.JLabel lblLeiras;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlLadak;
    // End of variables declaration//GEN-END:variables
}